"""add description column

Revision ID: 01c774450bc0
Revises: 306e1d9fed76
Create Date: 2023-02-11 20:17:40.369925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c774450bc0'
down_revision = '306e1d9fed76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'description')
    # ### end Alembic commands ###
